version: '3'
services:

  # TPM simulator
  ids-tpmsim-provider:
    image: fraunhoferaisec/tpmsim:${EXAMPLE_TAG:-develop}
    volumes:
      # Always extract a "clean state" for our TPM simulator to prevent DA lockout issues
      - ../tpmsim/tpmsim_data.tar:/tpmsim_data.tar
    networks:
      - provider-internal

  # The core platform, mounts docker control socket and route definition into the image
   # The core platform, mounts docker control socket and route definition into the image
  ecc-provider:
    image: market4.0/execution_core_container_business
    ports:
      - 8097:8097
      - 8887:8887
      - 8889:8889
      - 5006:5005
    environment:
      - SPRING_PROFILES_ACTIVE=PRODUCER_DOCKER
      - TPM_HOST=ids-tpmsim-provider
      - MULTIPART=mixed  #Data APP endpoint multipart/mixed content type
      - CLEARING_HOUSE=http://109.232.32.193:8280/data
      - SSL_KEY_PASSWORD=changeit
      - KEYSTORE_PASSWORD=password
      - CH=false
      - DAPS=false
      - WSS=false
      - IDSCP=true
      - WSSE=false
      - TTC_CONSUMER_HOST=ecc-consumer
      - TTC_CONSUMER_PORT=29292
    command: --spring.profiles.active=PRODUCER_DOCKER
    volumes:
      - /Users/ascatox/Documents/Sviluppo/workspace_idsa2/cert:/cert
      - /Users/ascatox/Documents/Sviluppo/workspace_idsa2/hash:/hash
      - ../tpmsim/rootCA.crt:/etc/rootca-cert.pem
  # provider-core:
  #   image: fraunhoferaisec/trusted-connector-core:${EXAMPLE_TAG:-develop}
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ../log/:/root/log/
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./system.properties:/root/etc/system.properties
  #     - ../tpmsim/rootCA.crt:/root/etc/rootca-cert.pem
  #     #- ../cert-stores/provider-keystore.p12:/root/etc/provider-keystore.p12
  #     # - ../cert-stores/truststore.p12:/root/etc/truststore.p12
  #     - ../cert-stores/ssl-server.jks:/root/etc/ssl-server.jks
  #     - ./example-provider-routes.xml:/root/deploy/example-provider-routes.xml
  #   environment:
  #     - TPM_HOST=ids-tpmsim-provider
    # Enable this lines for debugging or UI access from localhost
#    ports:
#      - "5005:5005"
#      - "8181:8181"
#      - "8443:8443"
    networks:
      - ids-wide
      - provider-internal

  # Mosquitto MQTT broker
  mqtt-broker:
    image: eclipse-mosquitto:latest
    networks:
      - provider-internal

  # Sensor data provider
  provider-app:
    image: fraunhoferaisec/example-client:${EXAMPLE_TAG:-develop}
    networks:
      - provider-internal

networks:
  ids-wide:
    driver: bridge
  provider-internal:
    driver: bridge
